import * as vscode from 'vscode';
import { Packageable } from '../packageable';
import { Workspace } from '../workspace/workspaceClass';
import { Timed } from '../timedView';
import { disable, update, notebookDecorations } from './timedViewUpdate';
import { v4 as uuidv4 } from 'uuid';
import { editNote,  addNote, removeNote } from './updateNoteContents';
import { Buff } from '../Buffer/bufferSource';
import { Renamable } from '../recyclingBin/recyclingBinView';
import { TabLabels } from '../tabLabels/tabLabels';
import { compareFsPath, defaultProgress, formatFsPathForCompare } from '../miscTools/help';
import { grepExtensionDirectory } from '../miscTools/grepExtensionDirectory';
import { WTNotebookSerializer } from './notebookApi/notebookSerializer';
import { capitalize } from '../intellisense/common';


export interface NotebookPanelNote {
    kind: 'note';
    noteId: string;
    title: string;
    aliases: string[];
    sections: NoteSection[];
    uri: vscode.Uri;
}

export interface NoteSection {
    kind: 'section';
    noteId: string,
    header: string;
    idx: number,
    bullets: BulletPoint[];
}

export interface BulletPoint {
    kind: 'bullet';
    noteId: string;
    sectionIdx: number;
    idx: number;
    text: string;
}

export interface NoteMatch {
    range: vscode.Range;
    note: NotebookPanelNote;
}

export class NotebookPanel 
implements 
    vscode.TreeDataProvider<NotebookPanelNote | NoteSection | BulletPoint>, 
    vscode.HoverProvider, Timed, Renamable<NotebookPanelNote>,
    vscode.ReferenceProvider
{
    addNote = addNote;
    removeNote = removeNote;
    editNote = editNote;

    enabled: boolean;
    update = update;
    disable = disable;

    static singleton: NotebookPanel;

    public matchedNotebook: { [index: string]: NoteMatch[] };
    protected nounsRegex: RegExp | undefined;

    public notebook: NotebookPanelNote[];
    protected notebookFolderPath: vscode.Uri;
    public view: vscode.TreeView<NotebookPanelNote | NoteSection | BulletPoint>;
    constructor (
        public workspace: Workspace,
        public context: vscode.ExtensionContext,
        protected serializer: WTNotebookSerializer
    ) {
        this.notebookFolderPath = workspace.notebookFolder;
        
        this.matchedNotebook = {};

        // Will be modified by TimedView
        this.enabled = true;

        // Read notebook from disk
        this.notebook = []; 
        this.view = {} as vscode.TreeView<NotebookPanelNote | NoteSection | BulletPoint>
        this._onDidChangeFile = new vscode.EventEmitter<vscode.FileChangeEvent[]>();
        NotebookPanel.singleton = this;

        this.context.subscriptions.push(notebookDecorations);
    }

    async renameResource (node?: NotebookPanelNote | undefined): Promise<void> {
        if (!node) return;
        
        const originalName = node.title;
        const newName = await vscode.window.showInputBox({
            placeHolder: originalName,
            prompt: `What would you like to rename note for '${originalName}'?`,
            ignoreFocusOut: false,
            value: originalName,
            valueSelection: [0, originalName.length]
        });
        if (!newName) return;

        node.title = newName;
        this.serializer.writeSingleNote(node);
        return this.refresh().then(() => {
            TabLabels.assignNamesForOpenTabs();
        });
    }

    async initialize () {
        this.notebook = await this.serializer.deserializeNotebookPanel(this.notebookFolderPath);
        this.nounsRegex = this.getNounsRegex();
        this.view = vscode.window.createTreeView(`wt.notebook.tree`, {
            treeDataProvider: this,
            canSelectMany: true,
            showCollapseAll: true,
        });
        this.context.subscriptions.push(this.view);
        this.context.subscriptions.push(vscode.languages.registerHoverProvider({
            language: 'wt',
        }, this));
        this.context.subscriptions.push(vscode.languages.registerHoverProvider({
            language: 'wtNote',
        }, this));

        this.context.subscriptions.push(vscode.languages.registerDefinitionProvider({
            language: 'wt',
        }, this));
        this.context.subscriptions.push(vscode.languages.registerDefinitionProvider({
            language: 'wtNote',
        }, this));

        this.context.subscriptions.push(vscode.languages.registerReferenceProvider({
            language: "wt",
        }, this));
        this.context.subscriptions.push(vscode.languages.registerReferenceProvider({
            language: "wtNote",
        }, this));

        this.registerCommands();
    }

    static getNewNoteId (): string {
        // Default id generated by 'uuid' cannot be used as a capture group name,
        //      so we need to map them to something usable
        const id = uuidv4();
        //@ts-ignore
        const mappedId = id.replaceAll('-', '');            // remove dashes
        return `a${mappedId}`;                              // add an 'a' to the beginning
    }

	public _onDidChangeFile: vscode.EventEmitter<vscode.FileChangeEvent[]>;
	get onDidChangeFile(): vscode.Event<vscode.FileChangeEvent[]> {
		return this._onDidChangeFile.event;
	}

	private _onDidChangeTreeData: vscode.EventEmitter<NotebookPanelNote | NoteSection | BulletPoint | undefined> = new vscode.EventEmitter<NotebookPanelNote | NoteSection | BulletPoint | undefined>();
	readonly onDidChangeTreeData: vscode.Event<NotebookPanelNote | NoteSection | BulletPoint | undefined> = this._onDidChangeTreeData.event;
	async refresh (reload: boolean = false) {
        if (reload) {
            this.notebook = await this.serializer.deserializeNotebookPanel(this.notebookFolderPath);
        }
        // Also update the nouns regex
        this.nounsRegex = this.getNounsRegex();
		this._onDidChangeTreeData.fire(undefined);
	}

    protected getNounPattern (note: NotebookPanelNote, withId: boolean = true) {
        const realAliases = note.aliases
            .map(a => a.trim())
            .filter(a => a.length > 0);

        const aliasesAddition = realAliases.length > 0 
            ? `|${realAliases.join('|')}`
            : ``;
        const idAddition = withId
            ? `?<${note.noteId}>`
            : ``;
        return `(${idAddition}${note.title}${aliasesAddition})`
    }

    private getNounsRegex (withId: boolean=true, withSeparator: boolean=true, subset?: NotebookPanelNote[]): RegExp {
        if (this.notebook.length === 0) {
            return /^_^/
        }
        const nounFragments = (subset || this.notebook).map(note => this.getNounPattern(note, withId))
        const regexString = withSeparator 
            ? '(^|[^a-zA-Z0-9])?' + `(${nounFragments.join('|')})` + '([^a-zA-Z0-9]|$)?'
            : `(${nounFragments.join('|')})`;
        const nounsRegex = new RegExp(regexString, 'gi');
        return nounsRegex;
    }

    private registerCommands () {

        const doTheThingAndWrite = async (f: () => Promise<string | null>) => {
            const result = await f();
            if (result === null) return;
            const noteId = result;

            const note = this.notebook.find(note => note.noteId === noteId);
            if (note === undefined) return;
            this.serializer.writeSingleNote(note);
        }
        this.context.subscriptions.push(vscode.commands.registerCommand("wt.notebook.addNote", (resource: NotebookPanelNote | undefined) => { doTheThingAndWrite(() => this.addNote(resource)) }));
        this.context.subscriptions.push(vscode.commands.registerCommand("wt.notebook.removeNote", (resource: NotebookPanelNote) => { doTheThingAndWrite(() => this.removeNote(resource)) }));
        this.context.subscriptions.push(vscode.commands.registerCommand('wt.notebook.search', (resource: NotebookPanelNote) => { this.searchInSearchPanel(resource) }));
        this.context.subscriptions.push(vscode.commands.registerCommand('wt.notebook.editNote', (resource: NotebookPanelNote | NoteSection | BulletPoint) => { this.editNote(resource) }));
        this.context.subscriptions.push(vscode.commands.registerCommand('wt.notebook.getNotebook', () => this));
        this.context.subscriptions.push(vscode.commands.registerCommand('wt.notebook.refresh', () => {
            return this.refresh(true);
        }));
    }

    getTreeItem(noteNode: NotebookPanelNote | NoteSection | BulletPoint): vscode.TreeItem {
        const editCommand: vscode.Command = {
            command: "wt.notebook.editNote",
            title: "Edit Note",
            arguments: [ noteNode ],
        };
        switch (noteNode.kind) {
            case 'note': 
                const aliasesString = noteNode.aliases.join(', ');
                return {
                    id: noteNode.noteId,
                    contextValue: 'note',
                    label: noteNode.title,
                    description: aliasesString,
                    collapsibleState: vscode.TreeItemCollapsibleState.Expanded,
                    tooltip: aliasesString.length !== 0 
                        ? `${noteNode.title} (${aliasesString})`
                        : `${noteNode.title}`,
                    command: editCommand
                }
            case 'bullet': return {
                id: `${noteNode.noteId}__${noteNode.sectionIdx}__${noteNode.kind}__${noteNode.idx}`,
                contextValue: noteNode.kind,
                label: noteNode.text,
                collapsibleState: vscode.TreeItemCollapsibleState.None,
                tooltip: noteNode.text,
                iconPath: new vscode.ThemeIcon("debug-breakpoint-disabled"),
                command: editCommand
            }
            case 'section': return {
                id: `${noteNode.noteId}__section__${noteNode.idx}`,
                contextValue: noteNode.kind,
                label: capitalize(noteNode.header),
                collapsibleState: vscode.TreeItemCollapsibleState.Expanded,
                tooltip: capitalize(noteNode.header),
                command: editCommand
            }
        }
    }
    getChildren(element?: NotebookPanelNote | NoteSection | BulletPoint | undefined): vscode.ProviderResult<(NotebookPanelNote | NoteSection | BulletPoint)[]> {
        if (!element) return this.notebook;
        switch (element.kind) {
            case 'note': 
                return element.sections;
            case 'section': 
                return element.bullets;
            case 'bullet':
                return [];
        }
    }

    getParent(element: NotebookPanelNote | NoteSection | BulletPoint): vscode.ProviderResult<NotebookPanelNote | NoteSection | BulletPoint> {
        if (element.kind === 'note') {
            return null;
        }
        return this.notebook.find(note => note.noteId === element.noteId);
    }

    getNote (noteUri: vscode.Uri): NotebookPanelNote | null {
        return this.notebook.find(note => {
            const thisUri = note.uri;
            return compareFsPath(thisUri, noteUri);
        }) || null;
    }

    async searchInSearchPanel (resource: NotebookPanelNote) {
        vscode.commands.executeCommand('workbench.action.findInFiles', {
            query: this.getNounPattern(resource, false),
            triggerSearch: true,
            filesToInclude: 'data/chapters/**, data/snips/**',
            isRegex: true,
            isCaseSensitive: false,
            matchWholeWord: true,
        });
    }


    provideHover(
        document: vscode.TextDocument, 
        position: vscode.Position, 
        token: vscode.CancellationToken
    ): vscode.ProviderResult<vscode.Hover> {
        if (!this.matchedNotebook) return null;

        const documentMatches = this.matchedNotebook[formatFsPathForCompare(document.uri)];
        if (!documentMatches) return null;

        const matchedNote = documentMatches.find(match => match.range.contains(position));
        if (!matchedNote) return null;
        if (this.view.visible) {
            this.view.reveal(matchedNote.note, {
                select: true,
                expand: true,
            });
        }
        return null;
    }

    provideDefinition (
        document: vscode.TextDocument, 
        position: vscode.Position, 
        token: vscode.CancellationToken
    ): vscode.ProviderResult<vscode.Definition | vscode.LocationLink[]> {
        if (!this.matchedNotebook) return null;

        const documentMatches = this.matchedNotebook[formatFsPathForCompare(document.uri)];
        if (!documentMatches) return null;

        const matchedNote = documentMatches.find(match => match.range.contains(position));
        if (!matchedNote) return null;
    
        if (this.view.visible) {
            this.view.reveal(matchedNote.note, {
                select: true,
                expand: true,
            });
        }
    
        const fileName = `${matchedNote.note.noteId}.wtnote`;
        const filePath = vscode.Uri.joinPath(this.notebookFolderPath, fileName);
        return <vscode.Definition>{
            uri: filePath,
            range: new vscode.Range(position, position),
        };
    }

    async provideReferences(
        document: vscode.TextDocument, 
        position: vscode.Position, 
        context: vscode.ReferenceContext, 
        token: vscode.CancellationToken
    ): Promise<vscode.Location[] | null> {
        if (!this.matchedNotebook) return null;
        
        const documentMatches = this.matchedNotebook[formatFsPathForCompare(document.uri)];
        if (!documentMatches) return null;

        const matchedNote = documentMatches.find(match => match.range.contains(position));
        if (!matchedNote) return null;

        return defaultProgress(`Collecting references for '${matchedNote.note.title}'`, async () => {
            const subsetNounsRegex = this.getNounsRegex(false, false, [ matchedNote.note ]);
            const grepLocations: vscode.Location[] = []; 
            for await (const loc of grepExtensionDirectory(subsetNounsRegex.source, true, true, true)) {
                if (loc === null) return null;
                grepLocations.push(loc);
            }
    
            // For some reason the reference provider needs the locations to be indexed one less than the results from the 
            //      grep of the nouns
            // Not sure why that is -- but subtracting one from each character index works here
            return grepLocations.map(loc => new vscode.Location(loc.uri, new vscode.Range(
                new vscode.Position(loc.range.start.line, Math.max(loc.range.start.character - 1, 0)),
                new vscode.Position(loc.range.end.line, Math.max(loc.range.end.character - 1, 0))
            )));
        });
    }
}