echo ".local/bufferSource.ts;"; 
test -f .local/bufferSource.ts;  echo $?;
echo ".local/fetchSource.ts;"; 
test -f .local/fetchSource.ts;  echo $?;
echo ".local/extension.ts"; 
test -f .local/extension.ts;  echo $?;
echo ".local/package-lock.json"; 
test -f .local/package-lock.json;  echo $?;
echo ".local/package.json"; 
test -f .local/package.json;  echo $?;
echo ".local/.vscode/extensions.json"; 
test -f .local/.vscode/extensions.json;  echo $?;
echo ".local/.vscode/launch.json"; 
test -f .local/.vscode/launch.json;  echo $?;
echo ".local/.vscode/settings.json"; 
test -f .local/.vscode/settings.json;  echo $?;
echo ".local/.vscode/tasks.json"; 
test -f .local/.vscode/tasks.json;  echo $?;
echo ".local/tsconfig.json;"; 
test -f .local/tsconfig.json;  echo $?;
echo ".local/export/exportDocuments.ts"; 
test -f .local/export/exportDocuments.ts;  echo $?;
echo ".local/export/exportFormView.ts"; 
test -f .local/export/exportFormView.ts;  echo $?;
echo ".local/import/importDropProvider.ts"; 
test -f .local/import/importDropProvider.ts;  echo $?;
echo ".local/import/importFiles.ts"; 
test -f .local/import/importFiles.ts;  echo $?;
echo ".local/import/importFileSystemView.ts"; 
test -f .local/import/importFileSystemView.ts;  echo $?;
echo ".local/import/importFormView.ts"; 
test -f .local/import/importFormView.ts;  echo $?;
echo ".local/importExport/types.ts"; 
test -f .local/importExport/types.ts;  echo $?;
echo ".local/importExport/exportWorkspace.ts"; 
test -f .local/importExport/exportWorkspace.ts;  echo $?;
echo ".local/importExport/importWorkspace.ts"; 
test -f .local/importExport/importWorkspace.ts;  echo $?;
echo ".local/gitTransactions.ts"; 
test -f .local/gitTransactions.ts;  echo $?;
echo ".local/ttsDebugger/debugger/activateTTSDebug.ts;"; 
test -f .local/ttsDebugger/debugger/activateTTSDebug.ts;  echo $?;
echo ".local/ttsDebugger/debugger/debugAdapter.ts "; 
test -f .local/ttsDebugger/debugger/debugAdapter.ts ;  echo $?;
echo ".local/ttsDebugger/debugger/debugExtention.ts"; 
test -f .local/ttsDebugger/debugger/debugExtention.ts;  echo $?;
echo ".local/ttsDebugger/debugger/ttsDebug.ts"; 
test -f .local/ttsDebugger/debugger/ttsDebug.ts;  echo $?;
echo ".local/ttsDebugger/debugger/ttsRuntime.ts"; 
test -f .local/ttsDebugger/debugger/ttsRuntime.ts;  echo $?;
echo ".local/ttsDebugger/debugSession.ts"; 
test -f .local/ttsDebugger/debugSession.ts;  echo $?;
echo ".local/ttsDebugger/tts/tts.ts"; 
test -f .local/ttsDebugger/tts/tts.ts;  echo $?;
echo ".local/ttsDebugger/tts/windows.ts"; 
test -f .local/ttsDebugger/tts/windows.ts;  echo $?;
echo ".local/ttsDebugger/tts/windowsCommand.ts"; 
test -f .local/ttsDebugger/tts/windowsCommand.ts;  echo $?;
echo ".local/tabLabels.ts;"; 
test -f .local/tabLabels.ts;  echo $?;
echo ".local/provideSynonyms.ts;"; 
test -f .local/provideSynonyms.ts;  echo $?;
echo ".local/workspaceClass.ts"; 
test -f .local/workspaceClass.ts;  echo $?;